version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: link-preview-js
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - main_network

networks:
  main_network:
    external: true
